# Generated by Django 4.2.9 on 2024-02-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0002_alter_category_id_alter_page_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="category",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="category",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
